# -*- coding: utf-8 -*-
"""
SSH Setup Manager — Automated SSH credential establishment for HandQ.

When an agent item requires SSH remote work, SSHContextProvider (a V2
ContextProvider) intercepts the item, establishes credentials, and
injects a context hint into the agent's per-item host context so the agent
knows exactly which credentials file to use and how to call the SSH tool.

Authentication flow (tried in order):
  1. Key auth  — paramiko auto-discovers ~/.ssh/id_* or uses key_path
  2. Keyring   — password fetched from OS keyring (if creds file has
                 keyring_service field and keyring entry exists)
  3. Password  — user prompted once (getpass on CLI, masked on UI);
                 password stored in keyring for future use

Credential file (auto-generated, never contains plaintext password):
  ~/.ssh/handq_<safe_hostname>.yaml
  Contents: hostname, username, [keyring_service]
  Permissions: 600

Keyring service name: handq-<safe_hostname>
  (hostname dots/colons replaced with underscores)
"""
from __future__ import annotations

import asyncio
import getpass
import os
import re
import sys
import textwrap
from dataclasses import dataclass
from typing import TYPE_CHECKING, Any, Dict, Optional

from ..controller_v2.context import ContextProvider, ItemContext, ProviderCache
from .logger import get_logger

if TYPE_CHECKING:
    from ..controller_v2.interaction_manager import InteractionManager

# ── Hard dependencies ────────────────────────────────────────────────────────

import paramiko as _paramiko
import yaml as _yaml
import keyring as _keyring


# ── Data classes ──────────────────────────────────────────────────────────────

@dataclass
class SSHReadyResult:
    """Returned by SSHSetupManager.ensure_ssh_ready() on success."""
    creds_file: str       # Absolute path to the auto-generated credentials YAML
    auth_method: str      # "key" | "keyring" | "password"
    hostname: str
    username: str
    context_hint: str     # String to append to effective_goal


class SSHSetupError(Exception):
    """Raised when SSH credential setup fails and the step cannot proceed."""


# ── Helpers ───────────────────────────────────────────────────────────────────

def _safe_hostname(hostname: str) -> str:
    """Convert hostname to a filesystem/keyring-safe identifier."""
    return re.sub(r"[^a-zA-Z0-9_-]", "_", hostname)


def _default_creds_path(hostname: str) -> str:
    return os.path.expanduser(f"~/.ssh/handq_{_safe_hostname(hostname)}.yaml")


def _keyring_service_name(hostname: str) -> str:
    return f"handq-{_safe_hostname(hostname)}"


def _write_creds_file(path: str, hostname: str, username: str,
                      port: int, keyring_service: Optional[str]) -> None:
    """Write (or overwrite) the credentials YAML file without a plaintext password."""
    lines = [
        "# Auto-generated by HandQ SSH Setup — do not add plaintext passwords here\n",
        f"hostname: {hostname}\n",
        f"username: {username}\n",
    ]
    if port != 22:
        lines.append(f"port: {port}\n")
    if keyring_service:
        lines.append(f"keyring_service: {keyring_service}\n")

    os.makedirs(os.path.dirname(path) if os.path.dirname(path) else ".", exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        fh.writelines(lines)
    try:
        os.chmod(path, 0o600)
    except Exception:
        pass  # Windows — permissions handled differently


def _setup_keyring_backend() -> None:
    """
    Ensure a usable keyring backend is active.

    Force PlaintextKeyring unless a proper OS-level keyring is available
    (Secret Service on Linux, Keychain on macOS, Credential Manager on Windows).
    EncryptedKeyring is intentionally avoided: it requires an interactive
    master-password prompt which blocks headless/background processes.
    The keyring file is protected by filesystem permissions (600).
    """
    backend = _keyring.get_keyring()
    module = backend.__class__.__module__.lower()
    name   = backend.__class__.__name__.lower()
    _SYSTEM_BACKENDS = ("secretservice", "kwallet", "keychain", "windows", "macos")
    if any(x in module or x in name for x in _SYSTEM_BACKENDS):
        return

    from keyrings.alt.file import PlaintextKeyring  # type: ignore
    _keyring.set_keyring(PlaintextKeyring())


def _probe_login_shell(
    hostname: str,
    username: str,
    port: int,
    password: Optional[str] = None,
    key_files: Optional[list] = None,
) -> str:
    """
    Probe the remote login shell after credentials are established.

    Makes a lightweight SSH connection (separate from the auth test) and runs
    ``echo __SHELL__$SHELL`` to read the $SHELL env variable.

    Returns one of: "bash" | "tcsh" | "zsh" | "sh" | "unknown".
    Never raises — returns "unknown" on any error.
    """
    try:
        client = _paramiko.SSHClient()
        client.set_missing_host_key_policy(_paramiko.AutoAddPolicy())
        kw: Dict[str, Any] = dict(
            hostname=hostname, port=port, username=username,
            timeout=10, banner_timeout=30, allow_agent=True, look_for_keys=False,
        )
        if key_files:
            kw["key_filename"] = key_files
            kw["allow_agent"] = False  # agent not needed when explicit keys provided
        if password:
            kw["password"] = password
            kw["allow_agent"] = False
        client.connect(**kw)
        _, stdout_ch, _ = client.exec_command("echo __SHELL__$SHELL", timeout=5)
        out = stdout_ch.read().decode("utf-8", errors="replace")
        client.close()
        if "__SHELL__" in out:
            shell_path = out.split("__SHELL__", 1)[-1].strip().lower()
            if "tcsh" in shell_path or "/csh" in shell_path:
                return "tcsh"
            elif "zsh" in shell_path:
                return "zsh"
            elif "bash" in shell_path:
                return "bash"
            elif shell_path.endswith("/sh") or shell_path == "sh":
                return "sh"
        return "unknown"
    except Exception:
        return "unknown"


def _try_connect(hostname: str, username: str, port: int,
                 password: Optional[str] = None,
                 key_files: Optional[list] = None) -> bool:
    """
    Attempt a paramiko connection.  Returns True on success, False on auth failure.
    Raises on network errors (host unreachable, timeout, etc.).
    """
    client = _paramiko.SSHClient()
    client.set_missing_host_key_policy(_paramiko.AutoAddPolicy())
    try:
        kw: Dict[str, Any] = dict(
            hostname=hostname, port=port, username=username,
            timeout=10, banner_timeout=30, allow_agent=True, look_for_keys=False,
        )
        if key_files:
            kw["key_filename"] = key_files
            kw["allow_agent"] = False  # agent not needed when explicit keys provided
        if password:
            kw["password"] = password
            kw["allow_agent"] = False
        client.connect(**kw)
        return True
    except _paramiko.AuthenticationException:
        return False
    finally:
        try:
            client.close()
        except Exception:
            pass


def _collect_default_key_files() -> list:
    return [
        os.path.expanduser(k)
        for k in ("~/.ssh/id_rsa", "~/.ssh/id_ed25519", "~/.ssh/id_ecdsa", "~/.ssh/id_dsa")
        if os.path.exists(os.path.expanduser(k))
    ]


def _build_context_hint(creds_file: str, auth_method: str, login_shell: str = "unknown") -> str:
    """First-time hint: minimal — credentials path, auth method, remote shell.

    The full SSH workflow lives in the ssh tool's usage_guide (single source of
    truth). We only inject what changes per host: the creds_file path, how we
    authenticated, and a non-bash advisory when relevant.
    """
    auth_label = {
        "key":      "key",
        "keyring":  "keyring",
        "password": "password (cached in keyring)",
    }.get(auth_method, auth_method)

    shell_note = f"shell={login_shell}" if login_shell != "unknown" else "shell=?"
    hint = (
        f"[SSH ready] credentials_file={creds_file} | auth={auth_label} | {shell_note}\n"
        f"Pass credentials_file in every ssh tool call."
    )

    if login_shell not in ("bash", "unknown", "powershell"):
        hint += (
            f"\nNOTE: remote shell is {login_shell}, not bash. For action='exec' "
            f"with custom commands wrap as: command='bash -c \"...\"'"
        )

    return hint


def _build_context_hint_brief(creds_file: str) -> str:
    """Minimal hint for subsequent steps — just the credentials file path."""
    return f'[SSH Context] credentials_file="{creds_file}"'


# ── SSHSetupManager ───────────────────────────────────────────────────────────

class SSHSetupManager:
    """
    Orchestrates the SSH credential establishment flow.

    Usage::

        manager = SSHSetupManager()
        result = await manager.ensure_ssh_ready(
            hostname="10.239.130.45",
            username="fengxuan",
            interaction_manager=im,
        )
        # result.creds_file  — path to write to agent goal
        # result.context_hint — string to inject into effective_goal
    """

    def __init__(self) -> None:
        self.logger = get_logger()

    async def ensure_ssh_ready(
        self,
        hostname: str,
        username: str,
        port: int = 22,
        creds_file: Optional[str] = None,
        interaction_manager: Optional["InteractionManager"] = None,
    ) -> SSHReadyResult:
        """
        Establish SSH credentials and return an SSHReadyResult.

        Steps:
          1. Determine credentials file path
          2. Try key auth (paramiko auto-discovers ~/.ssh/id_*)
          3. Try keyring auth (if creds file has keyring_service)
          4. Prompt user for password once → store in keyring → verify
        """
        _setup_keyring_backend()

        # Step 1: resolve creds file path
        if not creds_file:
            creds_file = _default_creds_path(hostname)
        creds_file = os.path.expanduser(creds_file)

        self.logger.info(
            f"SSH setup starting: {username}@{hostname}:{port} | creds_file={creds_file}",
            component="SSHSetupManager",
        )

        # Step 2: try key auth
        key_files = _collect_default_key_files()
        self.logger.debug(
            f"Attempting key auth for {username}@{hostname} | key_files={key_files}",
            component="SSHSetupManager",
        )
        try:
            if _try_connect(hostname, username, port, key_files=key_files or None):
                self.logger.info(
                    f"SSH key auth succeeded for {username}@{hostname}",
                    component="SSHSetupManager",
                )
                login_shell = _probe_login_shell(hostname, username, port, key_files=key_files or None)
                self.logger.info(
                    f"Remote login shell: {login_shell} ({username}@{hostname})",
                    component="SSHSetupManager",
                )
                _write_creds_file(creds_file, hostname, username, port, keyring_service=None)
                return SSHReadyResult(
                    creds_file=creds_file,
                    auth_method="key",
                    hostname=hostname,
                    username=username,
                    context_hint=_build_context_hint(creds_file, "key", login_shell=login_shell),
                )
        except SSHSetupError:
            raise
        except Exception as exc:
            # Network error — surface immediately
            self.logger.error(
                f"SSH network error reaching {hostname}:{port} — {exc}",
                component="SSHSetupManager",
            )
            raise SSHSetupError(
                f"Cannot reach {hostname}:{port} — {exc}"
            ) from exc

        self.logger.debug(
            f"Key auth failed for {username}@{hostname} — trying keyring",
            component="SSHSetupManager",
        )

        # Step 3: try keyring auth (if creds file exists with keyring_service)
        service = _keyring_service_name(hostname)
        if os.path.isfile(creds_file):
            existing_service = self._read_keyring_service(creds_file)
            if existing_service:
                try:
                    password = _keyring.get_password(existing_service, username)
                except Exception as _kr_exc:
                    self.logger.warning(
                        f"Keyring get_password failed ({_kr_exc}) — skipping keyring auth",
                        component="SSHSetupManager",
                    )
                    password = None
                if password:
                    self.logger.debug(
                        f"Attempting keyring auth for {username}@{hostname} "
                        f"| service={existing_service}",
                        component="SSHSetupManager",
                    )
                    try:
                        if _try_connect(hostname, username, port, password=password):
                            self.logger.info(
                                f"SSH keyring auth succeeded for {username}@{hostname}",
                                component="SSHSetupManager",
                            )
                            login_shell = _probe_login_shell(hostname, username, port, password=password)
                            self.logger.info(
                                f"Remote login shell: {login_shell} ({username}@{hostname})",
                                component="SSHSetupManager",
                            )
                            return SSHReadyResult(
                                creds_file=creds_file,
                                auth_method="keyring",
                                hostname=hostname,
                                username=username,
                                context_hint=_build_context_hint(creds_file, "keyring", login_shell=login_shell),
                            )
                    except SSHSetupError:
                        raise
                    except Exception as exc:
                        raise SSHSetupError(
                            f"Cannot reach {hostname}:{port} — {exc}"
                        ) from exc
                    # Password in keyring is stale — clear it
                    self.logger.warning(
                        f"Keyring password for {username}@{hostname} is stale — clearing",
                        component="SSHSetupManager",
                    )
                    try:
                        _keyring.delete_password(existing_service, username)
                    except Exception:
                        pass
                else:
                    self.logger.debug(
                        f"No keyring password found for {username}@{hostname} "
                        f"| service={existing_service}",
                        component="SSHSetupManager",
                    )
        else:
            self.logger.debug(
                f"Keyring auth skipped: creds_file_exists={os.path.isfile(creds_file)}",
                component="SSHSetupManager",
            )

        self.logger.warning(
            f"SSH key and keyring auth failed for {username}@{hostname} "
            f"— falling back to password prompt",
            component="SSHSetupManager",
        )

        # Step 4: prompt user for password — up to 3 attempts
        _MAX_ATTEMPTS = 3
        password = None
        for attempt in range(1, _MAX_ATTEMPTS + 1):
            candidate = await self._request_password_once(
                hostname=hostname,
                username=username,
                interaction_manager=interaction_manager,
                attempt=attempt,
                max_attempts=_MAX_ATTEMPTS,
            )
            if not candidate:
                raise SSHSetupError(
                    f"No password provided for {username}@{hostname}. SSH setup aborted."
                )

            try:
                ok = _try_connect(hostname, username, port, password=candidate)
            except SSHSetupError:
                raise
            except Exception as exc:
                raise SSHSetupError(
                    f"Connection to {hostname}:{port} failed: {exc}"
                ) from exc

            if ok:
                self.logger.info(
                    f"SSH password auth succeeded for {username}@{hostname} "
                    f"(attempt {attempt}/{_MAX_ATTEMPTS})",
                    component="SSHSetupManager",
                )
                password = candidate
                break

            self.logger.warning(
                f"SSH password auth failed for {username}@{hostname} "
                f"(attempt {attempt}/{_MAX_ATTEMPTS})",
                component="SSHSetupManager",
            )
            if attempt < _MAX_ATTEMPTS:
                print(
                    f"Authentication failed (attempt {attempt}/{_MAX_ATTEMPTS}). "
                    "Please try again.",
                    file=__import__("sys").stderr,
                )

        if password is None:
            self.logger.error(
                f"SSH auth failed for {username}@{hostname} after {_MAX_ATTEMPTS} attempts",
                component="SSHSetupManager",
            )
            raise SSHSetupError(
                f"Authentication failed for {username}@{hostname} "
                f"after {_MAX_ATTEMPTS} attempts."
            )

        # Store in keyring and write creds file
        try:
            _keyring.set_password(service, username, password)
            self.logger.info(
                f"SSH password stored in keyring | service={service}, user={username}",
                component="SSHSetupManager",
            )
            _write_creds_file(creds_file, hostname, username, port, keyring_service=service)
        except Exception as _kr_exc:
            self.logger.warning(
                f"Keyring set_password failed ({_kr_exc}) — saving creds without keyring",
                component="SSHSetupManager",
            )
            _write_creds_file(creds_file, hostname, username, port, keyring_service=None)

        login_shell = _probe_login_shell(hostname, username, port, password=password)
        self.logger.info(
            f"Remote login shell: {login_shell} ({username}@{hostname})",
            component="SSHSetupManager",
        )
        return SSHReadyResult(
            creds_file=creds_file,
            auth_method="password",
            hostname=hostname,
            username=username,
            context_hint=_build_context_hint(creds_file, "password", login_shell=login_shell),
        )

    def _read_keyring_service(self, creds_file: str) -> Optional[str]:
        """Read keyring_service field from an existing credentials YAML file."""
        try:
            with open(creds_file, "r", encoding="utf-8") as fh:
                data = _yaml.safe_load(fh) or {}
            return data.get("keyring_service")
        except Exception:
            return None

    async def _request_password_once(
        self,
        hostname: str,
        username: str,
        interaction_manager: Optional["InteractionManager"],
        attempt: int = 1,
        max_attempts: int = 1,
    ) -> str:
        """
        Prompt the user for a password (one attempt).

        Priority:
          1. InteractionManager.request_secret_input() — UI/TUI path (masked input)
          2. getpass.getpass()                         — CLI path (tty only)
          3. SSHSetupError                             — non-interactive; fail fast
        """
        attempt_suffix = f" (attempt {attempt}/{max_attempts})" if max_attempts > 1 else ""
        prompt_msg = (
            f"[HandQ] SSH password required for {username}@{hostname}{attempt_suffix}\n"
            f"  Password will be stored in the OS keyring — never written to disk"
        )

        # Always log + print to stderr so the prompt is visible in logs and
        # headless/regression environments regardless of UI mode.
        self.logger.warning(
            f"SSH password prompt: waiting for user input — {username}@{hostname} "
            f"(attempt {attempt}/{max_attempts})",
            component="SSHSetupManager",
        )
        print(
            f"\n[HandQ SSH] {prompt_msg}",
            file=sys.stderr, flush=True,
        )

        # UI path: use interaction_manager regardless of _ui attribute.
        # InteractionManager itself decides how to surface the prompt.
        if interaction_manager is not None:
            fn = getattr(interaction_manager, "request_secret_input", None)
            if fn is not None:
                self.logger.debug(
                    "Delegating SSH password prompt to InteractionManager.request_secret_input()",
                    component="SSHSetupManager",
                )
                result = await asyncio.get_event_loop().run_in_executor(
                    None, fn, prompt_msg
                )
                # If the UI delegate's request_secret_input is async (e.g. _BackgroundUI),
                # calling it via run_in_executor returns a coroutine object rather than a
                # string.  Await it here on the existing event loop.
                if asyncio.iscoroutine(result):
                    result = await result
                return result

        # CLI path: only when stdin is a real terminal — never block headless environments.
        if not sys.stdin.isatty():
            raise SSHSetupError(
                f"SSH password required for {username}@{hostname} but no interactive "
                f"terminal is available.\n"
                f"Pre-store the password with:\n"
                f"  python handq_keyring.py set handq-{_safe_hostname(hostname)} {username}"
            )

        def _getpass() -> str:
            print(prompt_msg)
            return getpass.getpass("  Password: ")

        return await asyncio.get_event_loop().run_in_executor(None, _getpass)


# ── SSHContextProvider ────────────────────────────────────────────────────────

# Regex to extract hostname/IP from step text — used as fallback by
# _extract_host_user when step.ssh_target is not explicitly set by the Planner.
_HOST_RE = re.compile(
    r"(?:(\w[\w.-]*)@)?"                    # optional user@
    r"((?:\d{1,3}\.){3}\d{1,3}"            # IPv4
    r"|(?:[a-zA-Z0-9](?:[a-zA-Z0-9-]*[a-zA-Z0-9])?\.)+[a-zA-Z]{2,}"  # FQDN
    r"|localhost)"
)

# Regex to extract username from "user@host" patterns (used for ssh_target parse).
_USER_AT_RE = re.compile(r"(\w[\w.-]*)@([\w.-]+)")


class SSHContextProvider(ContextProvider):
    """
    ContextProvider for SSH remote work.

    Activation: Planner declares "ssh" in tools_required (and should
    also set ``ssh_target`` on the item so before_item knows which host to
    authenticate against). FlowControllerV2 invokes before_item based purely
    on the declaration — there is no keyword safety net.

    Responsibility: establish SSH credentials (key/keyring/password) for
    the target host BEFORE the agent runs, so the ssh tool's connection
    pool can authenticate without prompting mid-execution. Per-hostname
    cache in the ProviderCache ensures subsequent items reuse the same
    credentials.
    """

    def __init__(self) -> None:
        self._manager = SSHSetupManager()
        self.logger = get_logger()

    @property
    def tool_name(self) -> str:
        return "ssh"

    async def before_item(
        self,
        ctx: ItemContext,
        im: "InteractionManager",
        cache: ProviderCache,
    ) -> Optional[str]:
        """
        Establish SSH credentials and return a context hint string.

        Progressive disclosure:
          - First time a hostname is seen: full hint (workflow guide + creds path)
          - Subsequent items for the same hostname: brief hint (creds path only)

        Per-hostname caching: credentials are stored keyed by hostname so
        parallel items targeting different hosts each receive the correct hint.
        """
        self.logger.info(
            f"SSHContextProvider.before_item() triggered for item {ctx.item_id!r}: "
            f"{ctx.instruction[:80]}",
            component="SSHContextProvider",
        )

        # Extract hostname and username from item context first so we can do
        # a per-hostname cache lookup.
        hostname, username = self._extract_host_user(ctx)
        if not hostname:
            # Cannot determine target host — skip injection silently.
            # The agent will have to figure it out from the instruction.
            self.logger.warning(
                f"SSHContextProvider: could not extract hostname from item "
                f"{ctx.item_id!r} — skipping SSH context injection. "
                f"Instruction (first 120): {ctx.instruction[:120]!r}",
                component="SSHContextProvider",
            )
            return None

        # Per-hostname cache check — returns brief hint if already established.
        cached = cache.get("ssh", hostname)
        if cached:
            self.logger.debug(
                f"Using cached SSH context for {hostname}: creds_file={cached['creds_file']}",
                component="SSHContextProvider",
            )
            return _build_context_hint_brief(cached["creds_file"])

        self.logger.info(
            f"SSHContextProvider: establishing credentials for "
            f"{username or '(unknown)'}@{hostname}",
            component="SSHContextProvider",
        )

        try:
            result = await self._manager.ensure_ssh_ready(
                hostname=hostname,
                username=username or "",
                interaction_manager=im,
            )
        except SSHSetupError as exc:
            # Surface the error as a hint so the agent can report it to the user.
            self.logger.error(
                f"SSH setup failed for {username or '?'}@{hostname}: {exc}",
                component="SSHContextProvider",
            )
            return (
                f"[SSH Setup Error]\n"
                f"Failed to establish SSH credentials: {exc}\n"
                f"Please verify the hostname, username, and password, then retry."
            )

        self.logger.info(
            f"SSH credentials ready via {result.auth_method}: {result.creds_file}",
            component="SSHContextProvider",
        )

        # Cache per hostname so parallel items targeting other hosts are unaffected.
        cache.set("ssh", hostname, {
            "creds_file": result.creds_file,
            "hint": result.context_hint,
        })
        return result.context_hint

    def _extract_host_user(self, ctx: ItemContext) -> tuple[str, str]:
        """
        Extract (hostname, username) from item context.

        Priority:
          1. ctx.ssh_target — structured field set by Planner ("user@hostname")
          2. user@host regex in instruction text
          3. bare IPv4 / FQDN regex
        Returns ("", "") if nothing found.
        """
        # Priority 1: structured field — fastest and most reliable path.
        ssh_target = ctx.ssh_target or ""
        if ssh_target.strip():
            m = _USER_AT_RE.match(ssh_target.strip())
            if m:
                return m.group(2), m.group(1)
            # Bare hostname (no user@) in ssh_target — use current OS user.
            host = ssh_target.strip()
            return host, getpass.getuser()

        text = ctx.instruction

        # Try user@host pattern first
        m = _USER_AT_RE.search(text)
        if m:
            return m.group(2), m.group(1)

        # Try bare host (IP or FQDN)
        m = _HOST_RE.search(text)
        if m:
            host = m.group(2) or ""
            user = m.group(1) or getpass.getuser()  # fall back to current OS user
            return host, user

        return "", ""
