# -*- coding: utf-8 -*-
"""
SSH Setup Manager — Automated SSH credential establishment for HandQ.

Round 5 (Phase 5E): credential setup moved from a per-item ContextProvider
hook into the ssh/remote_handq tools themselves. When an agent calls either
tool with ``ssh_target`` instead of an existing ``credentials_file``, the
tool calls ``ensure_ssh_credentials_lazy`` below directly — no Planner
declaration, no Coordinator-side hook, no pre-turn hint injection. The agent
learns the resolved ``credentials_file`` path from the tool's own return
value and passes it on subsequent calls.

Authentication flow (tried in order):
  1. Key auth  — paramiko auto-discovers ~/.ssh/id_* or uses key_path
  2. Keyring   — password fetched from OS keyring (if creds file has
                 keyring_service field and keyring entry exists)
  3. Password  — user prompted once (getpass on CLI, masked on UI);
                 password stored in keyring for future use

Credential file (auto-generated, never contains plaintext password):
  ~/.ssh/handq_<safe_hostname>.yaml
  Contents: hostname, username, [keyring_service]
  Permissions: 600

Keyring service name: handq-<safe_hostname>
  (hostname dots/colons replaced with underscores)
"""
from __future__ import annotations

import asyncio
import getpass
import os
import re
import sys
import textwrap
from dataclasses import dataclass
from typing import TYPE_CHECKING, Any, Dict, Optional

from .logger import get_logger

if TYPE_CHECKING:
    from ..controller_v2.interaction_manager import InteractionManager

# ── Hard dependencies ────────────────────────────────────────────────────────

import paramiko as _paramiko
import yaml as _yaml
import keyring as _keyring


# ── Data classes ──────────────────────────────────────────────────────────────

@dataclass
class SSHReadyResult:
    """Returned by SSHSetupManager.ensure_ssh_ready() on success."""
    creds_file: str       # Absolute path to the auto-generated credentials YAML
    auth_method: str      # "key" | "keyring" | "password"
    hostname: str
    username: str


class SSHSetupError(Exception):
    """Raised when SSH credential setup fails and the step cannot proceed."""


# ── Helpers ───────────────────────────────────────────────────────────────────

def _safe_hostname(hostname: str) -> str:
    """Convert hostname to a filesystem/keyring-safe identifier."""
    return re.sub(r"[^a-zA-Z0-9_-]", "_", hostname)


def _default_creds_path(hostname: str) -> str:
    return os.path.expanduser(f"~/.ssh/handq_{_safe_hostname(hostname)}.yaml")


def _keyring_service_name(hostname: str) -> str:
    return f"handq-{_safe_hostname(hostname)}"


def _write_creds_file(path: str, hostname: str, username: str,
                      port: int, keyring_service: Optional[str]) -> None:
    """Write (or overwrite) the credentials YAML file without a plaintext password."""
    lines = [
        "# Auto-generated by HandQ SSH Setup — do not add plaintext passwords here\n",
        f"hostname: {hostname}\n",
        f"username: {username}\n",
    ]
    if port != 22:
        lines.append(f"port: {port}\n")
    if keyring_service:
        lines.append(f"keyring_service: {keyring_service}\n")

    os.makedirs(os.path.dirname(path) if os.path.dirname(path) else ".", exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        fh.writelines(lines)
    try:
        os.chmod(path, 0o600)
    except Exception:
        pass  # Windows — permissions handled differently


def _setup_keyring_backend() -> None:
    """
    Ensure a usable keyring backend is active.

    Force PlaintextKeyring unless a proper OS-level keyring is available
    (Secret Service on Linux, Keychain on macOS, Credential Manager on Windows).
    EncryptedKeyring is intentionally avoided: it requires an interactive
    master-password prompt which blocks headless/background processes.
    The keyring file is protected by filesystem permissions (600).
    """
    backend = _keyring.get_keyring()
    module = backend.__class__.__module__.lower()
    name   = backend.__class__.__name__.lower()
    _SYSTEM_BACKENDS = ("secretservice", "kwallet", "keychain", "windows", "macos")
    if any(x in module or x in name for x in _SYSTEM_BACKENDS):
        return

    from keyrings.alt.file import PlaintextKeyring  # type: ignore
    _keyring.set_keyring(PlaintextKeyring())


def _probe_login_shell(
    hostname: str,
    username: str,
    port: int,
    password: Optional[str] = None,
    key_files: Optional[list] = None,
) -> str:
    """
    Probe the remote login shell after credentials are established.

    Makes a lightweight SSH connection (separate from the auth test) and runs
    ``echo __SHELL__$SHELL`` to read the $SHELL env variable.

    Returns one of: "bash" | "tcsh" | "zsh" | "sh" | "unknown".
    Never raises — returns "unknown" on any error.
    """
    try:
        client = _paramiko.SSHClient()
        client.set_missing_host_key_policy(_paramiko.AutoAddPolicy())
        kw: Dict[str, Any] = dict(
            hostname=hostname, port=port, username=username,
            timeout=10, banner_timeout=30, allow_agent=True, look_for_keys=False,
        )
        if key_files:
            kw["key_filename"] = key_files
            kw["allow_agent"] = False  # agent not needed when explicit keys provided
        if password:
            kw["password"] = password
            kw["allow_agent"] = False
        client.connect(**kw)
        _, stdout_ch, _ = client.exec_command("echo __SHELL__$SHELL", timeout=5)
        out = stdout_ch.read().decode("utf-8", errors="replace")
        client.close()
        if "__SHELL__" in out:
            shell_path = out.split("__SHELL__", 1)[-1].strip().lower()
            if "tcsh" in shell_path or "/csh" in shell_path:
                return "tcsh"
            elif "zsh" in shell_path:
                return "zsh"
            elif "bash" in shell_path:
                return "bash"
            elif shell_path.endswith("/sh") or shell_path == "sh":
                return "sh"
        return "unknown"
    except Exception:
        return "unknown"


def _try_connect(hostname: str, username: str, port: int,
                 password: Optional[str] = None,
                 key_files: Optional[list] = None) -> bool:
    """
    Attempt a paramiko connection.  Returns True on success, False on auth failure.
    Raises on network errors (host unreachable, timeout, etc.).
    """
    client = _paramiko.SSHClient()
    client.set_missing_host_key_policy(_paramiko.AutoAddPolicy())
    try:
        kw: Dict[str, Any] = dict(
            hostname=hostname, port=port, username=username,
            timeout=10, banner_timeout=30, allow_agent=True, look_for_keys=False,
        )
        if key_files:
            kw["key_filename"] = key_files
            kw["allow_agent"] = False  # agent not needed when explicit keys provided
        if password:
            kw["password"] = password
            kw["allow_agent"] = False
        client.connect(**kw)
        return True
    except _paramiko.AuthenticationException:
        return False
    finally:
        try:
            client.close()
        except Exception:
            pass


def _collect_default_key_files() -> list:
    return [
        os.path.expanduser(k)
        for k in ("~/.ssh/id_rsa", "~/.ssh/id_ed25519", "~/.ssh/id_ecdsa", "~/.ssh/id_dsa")
        if os.path.exists(os.path.expanduser(k))
    ]


# ── SSHSetupManager ───────────────────────────────────────────────────────────

class SSHSetupManager:
    """
    Orchestrates the SSH credential establishment flow.

    Usage::

        manager = SSHSetupManager()
        result = await manager.ensure_ssh_ready(
            hostname="10.239.130.45",
            username="fengxuan",
            interaction_manager=im,
        )
        # result.creds_file  — path to write to agent goal
    """

    def __init__(self) -> None:
        self.logger = get_logger()

    async def ensure_ssh_ready(
        self,
        hostname: str,
        username: str,
        port: int = 22,
        creds_file: Optional[str] = None,
        interaction_manager: Optional["InteractionManager"] = None,
    ) -> SSHReadyResult:
        """
        Establish SSH credentials and return an SSHReadyResult.

        Steps:
          1. Determine credentials file path
          2. Try key auth (paramiko auto-discovers ~/.ssh/id_*)
          3. Try keyring auth (if creds file has keyring_service)
          4. Prompt user for password once → store in keyring → verify
        """
        _setup_keyring_backend()

        # Step 1: resolve creds file path
        if not creds_file:
            creds_file = _default_creds_path(hostname)
        creds_file = os.path.expanduser(creds_file)

        self.logger.info(
            f"SSH setup starting: {username}@{hostname}:{port} | creds_file={creds_file}",
            component="SSHSetupManager",
        )

        # Step 2: try key auth
        key_files = _collect_default_key_files()
        self.logger.debug(
            f"Attempting key auth for {username}@{hostname} | key_files={key_files}",
            component="SSHSetupManager",
        )
        try:
            if _try_connect(hostname, username, port, key_files=key_files or None):
                self.logger.info(
                    f"SSH key auth succeeded for {username}@{hostname}",
                    component="SSHSetupManager",
                )
                login_shell = _probe_login_shell(hostname, username, port, key_files=key_files or None)
                self.logger.info(
                    f"Remote login shell: {login_shell} ({username}@{hostname})",
                    component="SSHSetupManager",
                )
                _write_creds_file(creds_file, hostname, username, port, keyring_service=None)
                return SSHReadyResult(
                    creds_file=creds_file,
                    auth_method="key",
                    hostname=hostname,
                    username=username,
                )
        except SSHSetupError:
            raise
        except Exception as exc:
            # Network error — surface immediately
            self.logger.error(
                f"SSH network error reaching {hostname}:{port} — {exc}",
                component="SSHSetupManager",
            )
            raise SSHSetupError(
                f"Cannot reach {hostname}:{port} — {exc}"
            ) from exc

        self.logger.debug(
            f"Key auth failed for {username}@{hostname} — trying keyring",
            component="SSHSetupManager",
        )

        # Step 3: try keyring auth (if creds file exists with keyring_service)
        service = _keyring_service_name(hostname)
        if os.path.isfile(creds_file):
            existing_service = self._read_keyring_service(creds_file)
            if existing_service:
                try:
                    password = _keyring.get_password(existing_service, username)
                except Exception as _kr_exc:
                    self.logger.warning(
                        f"Keyring get_password failed ({_kr_exc}) — skipping keyring auth",
                        component="SSHSetupManager",
                    )
                    password = None
                if password:
                    self.logger.debug(
                        f"Attempting keyring auth for {username}@{hostname} "
                        f"| service={existing_service}",
                        component="SSHSetupManager",
                    )
                    try:
                        if _try_connect(hostname, username, port, password=password):
                            self.logger.info(
                                f"SSH keyring auth succeeded for {username}@{hostname}",
                                component="SSHSetupManager",
                            )
                            login_shell = _probe_login_shell(hostname, username, port, password=password)
                            self.logger.info(
                                f"Remote login shell: {login_shell} ({username}@{hostname})",
                                component="SSHSetupManager",
                            )
                            return SSHReadyResult(
                                creds_file=creds_file,
                                auth_method="keyring",
                                hostname=hostname,
                                username=username,
                            )
                    except SSHSetupError:
                        raise
                    except Exception as exc:
                        raise SSHSetupError(
                            f"Cannot reach {hostname}:{port} — {exc}"
                        ) from exc
                    # Password in keyring is stale — clear it
                    self.logger.warning(
                        f"Keyring password for {username}@{hostname} is stale — clearing",
                        component="SSHSetupManager",
                    )
                    try:
                        _keyring.delete_password(existing_service, username)
                    except Exception:
                        pass
                else:
                    self.logger.debug(
                        f"No keyring password found for {username}@{hostname} "
                        f"| service={existing_service}",
                        component="SSHSetupManager",
                    )
        else:
            self.logger.debug(
                f"Keyring auth skipped: creds_file_exists={os.path.isfile(creds_file)}",
                component="SSHSetupManager",
            )

        self.logger.warning(
            f"SSH key and keyring auth failed for {username}@{hostname} "
            f"— falling back to password prompt",
            component="SSHSetupManager",
        )

        # Step 4: prompt user for password — up to 3 attempts
        _MAX_ATTEMPTS = 3
        password = None
        for attempt in range(1, _MAX_ATTEMPTS + 1):
            candidate = await self._request_password_once(
                hostname=hostname,
                username=username,
                interaction_manager=interaction_manager,
                attempt=attempt,
                max_attempts=_MAX_ATTEMPTS,
            )
            if not candidate:
                raise SSHSetupError(
                    f"No password provided for {username}@{hostname}. SSH setup aborted."
                )

            try:
                ok = _try_connect(hostname, username, port, password=candidate)
            except SSHSetupError:
                raise
            except Exception as exc:
                raise SSHSetupError(
                    f"Connection to {hostname}:{port} failed: {exc}"
                ) from exc

            if ok:
                self.logger.info(
                    f"SSH password auth succeeded for {username}@{hostname} "
                    f"(attempt {attempt}/{_MAX_ATTEMPTS})",
                    component="SSHSetupManager",
                )
                password = candidate
                break

            self.logger.warning(
                f"SSH password auth failed for {username}@{hostname} "
                f"(attempt {attempt}/{_MAX_ATTEMPTS})",
                component="SSHSetupManager",
            )
            if attempt < _MAX_ATTEMPTS:
                print(
                    f"Authentication failed (attempt {attempt}/{_MAX_ATTEMPTS}). "
                    "Please try again.",
                    file=__import__("sys").stderr,
                )

        if password is None:
            self.logger.error(
                f"SSH auth failed for {username}@{hostname} after {_MAX_ATTEMPTS} attempts",
                component="SSHSetupManager",
            )
            raise SSHSetupError(
                f"Authentication failed for {username}@{hostname} "
                f"after {_MAX_ATTEMPTS} attempts."
            )

        # Store in keyring and write creds file
        try:
            _keyring.set_password(service, username, password)
            self.logger.info(
                f"SSH password stored in keyring | service={service}, user={username}",
                component="SSHSetupManager",
            )
            _write_creds_file(creds_file, hostname, username, port, keyring_service=service)
        except Exception as _kr_exc:
            self.logger.warning(
                f"Keyring set_password failed ({_kr_exc}) — saving creds without keyring",
                component="SSHSetupManager",
            )
            _write_creds_file(creds_file, hostname, username, port, keyring_service=None)

        login_shell = _probe_login_shell(hostname, username, port, password=password)
        self.logger.info(
            f"Remote login shell: {login_shell} ({username}@{hostname})",
            component="SSHSetupManager",
        )
        return SSHReadyResult(
            creds_file=creds_file,
            auth_method="password",
            hostname=hostname,
            username=username,
        )

    def _read_keyring_service(self, creds_file: str) -> Optional[str]:
        """Read keyring_service field from an existing credentials YAML file."""
        try:
            with open(creds_file, "r", encoding="utf-8") as fh:
                data = _yaml.safe_load(fh) or {}
            return data.get("keyring_service")
        except Exception:
            return None

    async def _request_password_once(
        self,
        hostname: str,
        username: str,
        interaction_manager: Optional["InteractionManager"],
        attempt: int = 1,
        max_attempts: int = 1,
    ) -> str:
        """
        Prompt the user for a password (one attempt).

        Priority:
          1. InteractionManager.request_secret_input() — UI/TUI path (masked input)
          2. getpass.getpass()                         — CLI path (tty only)
          3. SSHSetupError                             — non-interactive; fail fast
        """
        attempt_suffix = f" (attempt {attempt}/{max_attempts})" if max_attempts > 1 else ""
        prompt_msg = (
            f"[HandQ] SSH password required for {username}@{hostname}{attempt_suffix}\n"
            f"  Password will be stored in the OS keyring — never written to disk"
        )

        # Always log + print to stderr so the prompt is visible in logs and
        # headless/regression environments regardless of UI mode.
        self.logger.warning(
            f"SSH password prompt: waiting for user input — {username}@{hostname} "
            f"(attempt {attempt}/{max_attempts})",
            component="SSHSetupManager",
        )
        print(
            f"\n[HandQ SSH] {prompt_msg}",
            file=sys.stderr, flush=True,
        )

        # UI path: use interaction_manager regardless of _ui attribute.
        # InteractionManager itself decides how to surface the prompt.
        if interaction_manager is not None:
            fn = getattr(interaction_manager, "request_secret_input", None)
            if fn is not None:
                self.logger.debug(
                    "Delegating SSH password prompt to InteractionManager.request_secret_input()",
                    component="SSHSetupManager",
                )
                result = await asyncio.get_event_loop().run_in_executor(
                    None, fn, prompt_msg
                )
                # If the UI delegate's request_secret_input is async (e.g. _BackgroundUI),
                # calling it via run_in_executor returns a coroutine object rather than a
                # string.  Await it here on the existing event loop.
                if asyncio.iscoroutine(result):
                    result = await result
                return result

        # CLI path: only when stdin is a real terminal — never block headless environments.
        if not sys.stdin.isatty():
            raise SSHSetupError(
                f"SSH password required for {username}@{hostname} but no interactive "
                f"terminal is available.\n"
                f"Pre-store the password with:\n"
                f"  python handq_keyring.py set handq-{_safe_hostname(hostname)} {username}"
            )

        def _getpass() -> str:
            print(prompt_msg)
            return getpass.getpass("  Password: ")

        return await asyncio.get_event_loop().run_in_executor(None, _getpass)


# ── Lazy credential setup (called directly by ssh_tool / remote_handq_tool) ──

# Regex to extract hostname/IP from free text — used as fallback when the
# caller passes a bare host or the target has to be parsed out of a string.
_HOST_RE = re.compile(
    r"(?:(\w[\w.-]*)@)?"                    # optional user@
    r"((?:\d{1,3}\.){3}\d{1,3}"            # IPv4
    r"|(?:[a-zA-Z0-9](?:[a-zA-Z0-9-]*[a-zA-Z0-9])?\.)+[a-zA-Z]{2,}"  # FQDN
    r"|localhost)"
)

# Regex to extract username from "user@host" patterns.
_USER_AT_RE = re.compile(r"(\w[\w.-]*)@([\w.-]+)")

# Process-lifetime manager instance — credential establishment has no
# per-session state (it writes a creds file + keyring entry, both durable
# across sessions), so one shared instance is sufficient.
_manager = SSHSetupManager()

# Per-hostname in-memory cache so a second call to the same host within the
# same process skips re-probing key/keyring auth. Keyed by "user@host" (or
# "host" when no user was given).
_lazy_cache: Dict[str, str] = {}


def parse_ssh_target(ssh_target: str) -> tuple[str, str]:
    """Extract (hostname, username) from a ``"user@host"`` or bare-host string.

    Returns ("", "") if *ssh_target* is empty or unparseable.
    """
    target = (ssh_target or "").strip()
    if not target:
        return "", ""
    m = _USER_AT_RE.match(target)
    if m:
        return m.group(2), m.group(1)
    return target, getpass.getuser()


async def ensure_ssh_credentials_lazy(
    ssh_target: str,
    interaction_manager: Optional["InteractionManager"],
) -> str:
    """Establish SSH credentials for *ssh_target* and return the creds file path.

    Called directly by ``ssh_tool`` / ``remote_handq_tool`` when the agent
    passes ``ssh_target`` instead of an already-resolved ``credentials_file``.
    No Planner declaration and no Coordinator-side hook are involved — the
    tool call itself triggers key/keyring/password establishment, prompting
    the user via *interaction_manager* only if neither key nor keyring auth
    succeeds.

    Raises ``SSHSetupError`` on failure (network unreachable, auth exhausted).
    """
    hostname, username = parse_ssh_target(ssh_target)
    if not hostname:
        raise SSHSetupError(
            f"Could not parse ssh_target={ssh_target!r} — expected "
            f"'user@host' or a bare hostname/IP."
        )

    cache_key = f"{username}@{hostname}" if username else hostname
    cached = _lazy_cache.get(cache_key)
    if cached:
        return cached

    result = await _manager.ensure_ssh_ready(
        hostname=hostname,
        username=username or "",
        interaction_manager=interaction_manager,
    )
    _lazy_cache[cache_key] = result.creds_file
    return result.creds_file

