"""Rule migrations — retroactive memory hygiene declarative pipeline.

Mental model
------------
SQLite gets ``schema.py:MIGRATIONS`` for STRUCTURE changes (new tables,
new columns). This file is its sibling for RULE changes (the triage
prompt got stricter, a new code-side guard was added, a duplicate
pattern needs cleanup).

Each :class:`RuleMigration` is a versioned, append-only audit pass over
existing entries. It emits :class:`CorrectionProposal` rows; the
:class:`RetriageWorker` decides which to auto-apply (per
``CORRECTION_AUTO_APPLY_TIER``) and writes the rest to
``correction_proposals`` for explicit review.

Append-only invariant
---------------------
Once a migration has shipped (a release went out with version N), do not
edit ``_mNNN_*``. Different users may be at different ``triage_rules_version``
values; rewriting an old migration silently rebuilds their corpus
differently from what the audit log says happened. Add ``_m{N+1}_*``
instead and let the new pass take over.

Auto-apply tiers
----------------
A migration declares ``auto_apply_kinds`` — the subset of
``CorrectionKind`` whose proposals the RetriageWorker auto-applies for
this migration. Convention:

- {ARCHIVE} for *deterministic* corrections (math says it; no judgment).
  Example: archiving an L2 source whose synthesis row already cites it.
- ``set()`` for everything else — propose-only, accumulating until a
  user (via UI or admin CLI) explicitly approves.

Even when a kind IS in ``auto_apply_kinds``, the global setting
``CORRECTION_AUTO_APPLY_TIER`` can downgrade to PROPOSAL_ONLY. The
migration's declaration is the upper bound; runtime config is the
ceiling.
"""
from __future__ import annotations

import asyncio
import json
import logging
import time
import uuid
from dataclasses import dataclass
from typing import AsyncIterator, Callable, List, Set

from .models import (
    CorrectionKind,
    CorrectionProposal,
    CorrectionStatus,
    EntryKind,
)

_logger = logging.getLogger("handq.ltm.rule_migrations")


# A migration's audit() is an async generator yielding **unsaved**
# CorrectionProposal instances. The worker handles persistence + PII
# scrub + auto-apply gating uniformly.
AuditFn = Callable[..., AsyncIterator[CorrectionProposal]]


@dataclass
class RuleMigration:
    """One versioned data-hygiene rule. Append to ``RULE_MIGRATIONS``.

    Fields
    ------
    version
        1-indexed. MUST be unique and monotonic across the list. Stored
        in ``correction_proposals.rule_version`` for traceability.
    name
        Short stable slug (snake_case). Embedded in
        ``archived_reason='correction_v{N}_{name}'`` so SQL rollback can
        target a specific migration.
    is_llm
        True if ``audit`` calls a helper LLM. The worker wires the LLM
        services in only when needed (no LLM cost for pure-Python passes).
    auto_apply_kinds
        Set of :class:`CorrectionKind` whose proposals can be auto-applied
        for this migration. Empty set = propose-only.
    description
        One-line human-readable purpose; surfaces in IPC / admin output.
    audit
        Async generator. Signature: ``audit(store, llm_services, **kwargs)
        -> AsyncIterator[CorrectionProposal]``. The worker passes
        ``llm_services=None`` when ``is_llm`` is False.
    """
    version: int
    name: str
    is_llm: bool
    auto_apply_kinds: Set[CorrectionKind]
    description: str
    audit: AuditFn


# ── v1: archive activity-log L2 entries ────────────────────────────────────

_M1_JUDGE_SYSTEM = """\
You judge whether a synthesised L2 memory/knowledge entry is a durable
user-profile / project-fact point OR merely an activity log.

An L2 entry is generated by clustering multiple L0 observations. Under the
new synthesis rules, L2 entries must help a future AI agent execute tasks
better. Entries that merely RECORD what the user did (browsing files,
using tools without stated preference, reviewing docs) are NOT durable.

Output a SINGLE JSON object. No prose, no markdown fences.

{
  "durable"   : <bool>,
  "confidence": <float 0.0-1.0>,
  "reason"    : "<short rationale, max 100 chars>"
}

## durable=true when the entry expresses:

- A stable user PREFERENCE (coding style, tool choice with reason,
  communication style)
- An environment CONSTRAINT the agent must respect (OS, paths, infra)
- A recurring MISTAKE PATTERN to avoid
- A stable working-style trait

## durable=false when the entry is:

- ACTIVITY LOG: records what happened without extracting a preference
  ("Team reviews design docs", "User browses ML artifacts")
- TOOL INVENTORY without preference signal ("Team uses WindTerm SSH")
- STALE: bound to a specific project phase already complete
- TRIVIALLY DERIVABLE from project files / codebase inspection

## confidence
- 0.90+ : clear-cut (obvious activity log or obvious durable preference)
- 0.70-0.89 : moderately confident
- <0.70 : uncertain; err toward durable=true (keep) to avoid mis-archives

Be conservative — mis-archived durable entries are recoverable but
noisy. Only mark durable=false when the entry is genuinely
activity-log-shaped.
"""


async def _m1_archive_stale_l2_audit(
    store, llm_services, **kwargs,
) -> AsyncIterator[CorrectionProposal]:
    """Audit L2 entries; propose archival for activity-log style entries.

    Judgment is LLM-driven. We propose ARCHIVE with confidence from the
    LLM's verdict — the RetriageWorker's HIGH_CONF tier gate (0.80 floor)
    decides whether to auto-apply.
    """
    run_id = kwargs.get("run_id", "")
    in_flight = kwargs.get("in_flight_entry_ids", set())

    rows = await store._fetchall(
        "SELECT id, kind, summary, version, archived FROM mem_entries "
        "WHERE synthesis_level=2 AND archived=0 "
        "ORDER BY created_at ASC"
    )
    _logger.info(
        "m1_archive_stale_l2: scanning %d active L2 entries", len(rows),
    )

    if not llm_services:
        _logger.warning("m1_archive_stale_l2: no LLM services; skipping")
        return

    from src.infrastructure.llm_pool import call_with_fallback

    for eid, kind_str, summary, version, archived in rows:
        if eid in in_flight:
            _logger.debug("m1: skip in-flight entry %s", eid[:8])
            continue

        # Fetch content for context
        chunks = await store._fetchall(
            "SELECT text FROM mem_chunks WHERE entry_id=? ORDER BY chunk_index",
            (eid,),
        )
        content = "\n".join(c[0] for c in chunks)[:1500]

        user_prompt = (
            f"L2 entry to judge:\n\n"
            f"Summary: {summary}\n\n"
            f"Content:\n{content}\n\n"
            f"Output JSON verdict."
        )

        try:
            result = await asyncio.wait_for(
                call_with_fallback(
                    llm_services,
                    dict(
                        messages=[
                            {"role": "system", "content": _M1_JUDGE_SYSTEM},
                            {"role": "user", "content": user_prompt},
                        ],
                        json_mode=True,
                        max_tokens=200,
                    ),
                ),
                timeout=60.0,
            )
        except asyncio.TimeoutError:
            _logger.warning("m1: LLM timeout for entry %s", eid[:8])
            continue
        except Exception:
            _logger.exception("m1: LLM call failed for entry %s", eid[:8])
            continue

        raw = (result.content or "").strip()
        try:
            verdict = json.loads(raw)
        except (json.JSONDecodeError, ValueError):
            _logger.debug("m1: unparseable verdict for %s: %r", eid[:8], raw[:100])
            continue

        durable = bool(verdict.get("durable", True))
        confidence = float(verdict.get("confidence", 0.0) or 0.0)
        reason = str(verdict.get("reason", ""))[:200]

        if durable:
            continue  # keep — no proposal needed

        # Propose ARCHIVE for the non-durable L2
        try:
            target_kind = EntryKind(kind_str)
        except ValueError:
            _logger.warning("m1: unknown kind %r for entry %s", kind_str, eid[:8])
            continue

        yield CorrectionProposal(
            id=str(uuid.uuid4()),
            kind=CorrectionKind.ARCHIVE,
            target_kind=target_kind,
            target_entry_id=eid,
            target_version=int(version or 1),
            target_archived=bool(archived),
            payload={"superseded_by_id": None},
            confidence=confidence,
            rule_version=1,
            parent_run_id=run_id,
            rationale=f"stale_l2: {reason}",
            rationale_pii_scrubbed=False,
            status=CorrectionStatus.PENDING,
            created_at=int(time.time()),
        )


# Append-only list. Each entry's ``version`` MUST be its 1-based index.
RULE_MIGRATIONS: List[RuleMigration] = [
    RuleMigration(
        version=1,
        name="archive_stale_l2",
        is_llm=True,
        auto_apply_kinds={CorrectionKind.ARCHIVE},
        description=(
            "Archive L2 synthesis entries that are activity logs rather than "
            "durable user-profile / project-fact points. Judgment is LLM-driven; "
            "HIGH_CONF (0.80+) proposals auto-apply, lower confidence proposals "
            "accumulate for review."
        ),
        audit=_m1_archive_stale_l2_audit,
    ),
]
